"use client";

import { useCallback, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { Download, FileText, Lock, ShieldCheck } from "lucide-react";

interface GalleryPhoto {
  id: string;
  url: string | null;
  mime_type: string | null;
  captured_at: string | null;
  sha256_hash: string | null;
  verification_code: string | null;
  gps_lat: number | null;
  gps_lng: number | null;
}

interface GalleryMeta {
  id: string;
  name: string;
  description: string | null;
  brand_watermark: boolean;
}

interface GalleryCompany {
  name: string;
  logo: string | null;
}

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || "";
const ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "";

export default function PublicGalleryPage() {
  const { token } = useParams<{ token: string }>();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [needsPassword, setNeedsPassword] = useState(false);
  const [passwordInput, setPasswordInput] = useState("");
  const [password, setPassword] = useState("");
  const [gallery, setGallery] = useState<GalleryMeta | null>(null);
  const [photos, setPhotos] = useState<GalleryPhoto[]>([]);
  const [company, setCompany] = useState<GalleryCompany | null>(null);
  const [selected, setSelected] = useState<GalleryPhoto | null>(null);
  const [pdfLoading, setPdfLoading] = useState(false);

  const fetchGallery = useCallback(
    async (pwd: string) => {
      if (!token) return;
      setLoading(true);
      setError(null);
      try {
        const url = new URL(`${SUPABASE_URL}/functions/v1/galleries/public`);
        url.searchParams.set("token", token);
        if (pwd) url.searchParams.set("password", pwd);
        const res = await fetch(url.toString(), {
          headers: { apikey: ANON_KEY },
        });
        const data = await res.json();

        if (res.status === 401 && data.status === "password_required") {
          setNeedsPassword(true);
          setLoading(false);
          return;
        }
        if (!res.ok) {
          setError(data.message || "This gallery is unavailable.");
          setLoading(false);
          return;
        }

        setGallery(data.gallery);
        setPhotos(data.photos || []);
        setCompany(data.company || null);
        setNeedsPassword(false);
      } catch {
        setError("Failed to load gallery. Please try again.");
      } finally {
        setLoading(false);
      }
    },
    [token],
  );

  useEffect(() => {
    void fetchGallery("");
  }, [fetchGallery]);

  async function handleDownloadPdf() {
    if (!gallery) return;
    setPdfLoading(true);
    try {
      // Public gallery can't call `reports` (needs auth). Instead, link the
      // staff-facing reports UI — public packet PDFs must be generated by the
      // tenant before sharing. Show a helpful message rather than a broken
      // button to set correct expectations.
      window.alert(
        "PDF packets are generated by the project team before sharing. Contact the sender if you need one.",
      );
    } finally {
      setPdfLoading(false);
    }
  }

  if (loading) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-stone-50">
        <div className="h-8 w-8 animate-spin rounded-full border-4 border-amber-500 border-t-transparent" />
      </div>
    );
  }

  if (needsPassword) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-stone-50 px-4">
        <form
          className="w-full max-w-sm rounded-2xl bg-white p-8 shadow-sm"
          onSubmit={(e) => {
            e.preventDefault();
            setPassword(passwordInput);
            void fetchGallery(passwordInput);
          }}
        >
          <div className="mb-5 flex items-center gap-2">
            <Lock size={18} className="text-amber-500" />
            <h1 className="text-lg font-bold text-slate-900">Password required</h1>
          </div>
          <p className="mb-4 text-sm text-slate-500">
            This gallery is password-protected. Enter the password you were given.
          </p>
          <input
            type="password"
            value={passwordInput}
            onChange={(e) => setPasswordInput(e.target.value)}
            className="w-full rounded-lg border border-stone-200 px-3 py-2 text-sm focus:border-amber-500 focus:outline-none"
            placeholder="Password"
            autoFocus
          />
          <button
            type="submit"
            className="mt-4 w-full rounded-lg bg-amber-500 py-2 text-sm font-semibold text-white hover:bg-amber-600"
          >
            Unlock gallery
          </button>
          {error && <p className="mt-3 text-xs text-red-500">{error}</p>}
        </form>
      </div>
    );
  }

  if (error || !gallery) {
    return (
      <div className="flex min-h-screen flex-col items-center justify-center bg-stone-50 px-4 text-center">
        <div className="rounded-2xl bg-white p-10 shadow-sm">
          <div className="mb-4 text-4xl">🔒</div>
          <h1 className="text-xl font-bold text-slate-900">Gallery unavailable</h1>
          <p className="mt-2 text-slate-500">{error || "This gallery is no longer active."}</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-stone-50">
      {/* Branded header */}
      <div className="border-b border-stone-200 bg-white px-6 py-4">
        <div className="mx-auto flex max-w-5xl items-center justify-between">
          <div className="flex items-center gap-3">
            {company?.logo && (
              <img
                src={company.logo}
                alt={company.name}
                className="h-8 w-8 rounded-lg object-cover"
              />
            )}
            <div>
              <p className="text-xs font-medium text-slate-500">{company?.name}</p>
              <p className="text-sm font-bold text-slate-900">{gallery.name}</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleDownloadPdf}
              disabled={pdfLoading}
              className="flex items-center gap-1.5 rounded-lg border border-stone-200 bg-white px-3 py-1.5 text-xs font-medium text-slate-700 hover:bg-stone-50"
            >
              <FileText size={14} /> PDF packet
            </button>
          </div>
        </div>
      </div>

      <div className="mx-auto max-w-5xl space-y-6 px-6 py-8">
        {gallery.description && (
          <p className="rounded-2xl bg-white p-5 text-sm text-slate-600 shadow-sm">
            {gallery.description}
          </p>
        )}

        <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4">
          {photos.map((p) => (
            <button
              key={p.id}
              onClick={() => setSelected(p)}
              className="group relative aspect-square overflow-hidden rounded-xl bg-stone-200 shadow-sm"
            >
              {p.url ? (
                // eslint-disable-next-line @next/next/no-img-element
                <img
                  src={p.url}
                  alt={p.verification_code || "photo"}
                  className="h-full w-full object-cover transition group-hover:scale-105"
                />
              ) : (
                <div className="flex h-full w-full items-center justify-center text-xs text-stone-400">
                  unavailable
                </div>
              )}
              {gallery.brand_watermark && company?.logo && (
                <img
                  src={company.logo}
                  alt=""
                  className="pointer-events-none absolute bottom-2 right-2 h-6 w-6 rounded bg-white/80 p-0.5"
                />
              )}
              <div className="absolute bottom-1 left-1 rounded bg-black/50 px-1.5 py-0.5 text-[10px] font-mono text-white">
                #{p.verification_code || "—"}
              </div>
            </button>
          ))}
        </div>

        <p className="flex items-center gap-2 pt-4 text-xs text-slate-400">
          <ShieldCheck size={12} />
          Every photo is verified by SHA-256 hash and a unique code — tamper-evident chain of custody.
        </p>
      </div>

      {selected && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-6"
          onClick={() => setSelected(null)}
        >
          <div
            className="max-h-[90vh] max-w-4xl overflow-hidden rounded-2xl bg-white"
            onClick={(e) => e.stopPropagation()}
          >
            {selected.url && (
              // eslint-disable-next-line @next/next/no-img-element
              <img src={selected.url} alt="" className="max-h-[70vh] w-full object-contain" />
            )}
            <div className="space-y-1 p-5 text-sm">
              <p className="font-mono text-xs text-slate-500">
                #{selected.verification_code || "—"}
              </p>
              {selected.captured_at && (
                <p className="text-slate-600">
                  Captured {new Date(selected.captured_at).toLocaleString()}
                </p>
              )}
              {selected.sha256_hash && (
                <p className="break-all font-mono text-[10px] text-slate-400">
                  sha256 {selected.sha256_hash}
                </p>
              )}
              {selected.url && (
                <a
                  href={selected.url}
                  download
                  className="mt-3 inline-flex items-center gap-1.5 rounded-lg bg-slate-900 px-3 py-1.5 text-xs font-semibold text-white hover:bg-slate-800"
                >
                  <Download size={14} /> Download original
                </a>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
