#!/usr/bin/env python3
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SUPABASE_DIR = REPO_ROOT / "infra" / "supabase"
MIGRATIONS_DIR = SUPABASE_DIR / "migrations"
SEED_FILE = SUPABASE_DIR / "seed.sql"
OUTPUT_DIR = SUPABASE_DIR / "generated"
SCHEMA_OUTPUT = OUTPUT_DIR / "full_schema.sql"
SCHEMA_WITH_SEED_OUTPUT = OUTPUT_DIR / "full_schema_with_seed.sql"

HEADER = """-- GENERATED FILE — DO NOT EDIT MANUALLY
-- Source: infra/supabase/migrations/*.sql
-- Generated by: python3 scripts/generate_supabase_sql_snapshot.py
--
-- Purpose:
--   full_schema.sql            -> hosted staging / production bootstrap
--   full_schema_with_seed.sql  -> local/demo bootstrap including seed data
--
-- SAFETY: This file is wrapped in a single transaction. If any
-- statement fails, the whole paste rolls back — no half-applied
-- schema. Safe to retry after fixing the failing statement.

BEGIN;
"""

FOOTER = """
COMMIT;
"""

SEED_WARNING_BANNER = """
-- ============================================================
-- !! DO NOT PASTE THIS FILE INTO HOSTED / PRODUCTION SUPABASE !!
-- ============================================================
-- This file contains seed data (test users, demo jobs, fake
-- auth.users rows with crypt('password123')). Applying it to a
-- hosted environment will create real login accounts with a
-- known password and is a security incident waiting to happen.
--
-- For hosted staging / production, use full_schema.sql instead.
-- For local development, apply via `supabase db reset` rather
-- than pasting this file.
-- ============================================================
"""


@dataclass(frozen=True)
class SnapshotResult:
    migration_count: int
    schema_output: Path
    schema_with_seed_output: Path


def list_migration_files(migrations_dir: Path = MIGRATIONS_DIR) -> list[Path]:
    return sorted(
        path
        for path in migrations_dir.glob("*.sql")
        if path.is_file()
    )


def render_snapshot(
    migration_files: list[Path],
    include_seed: bool,
    seed_file: Path,
) -> str:
    chunks: list[str] = []
    if include_seed:
        chunks.append(SEED_WARNING_BANNER.strip())
        chunks.append("")
    chunks.append(HEADER.strip())
    chunks.append("")

    for path in migration_files:
        chunks.extend(
            [
                f"-- >>> BEGIN MIGRATION: {path.name}",
                path.read_text().rstrip(),
                f"-- <<< END MIGRATION: {path.name}",
                "",
            ]
        )

    if include_seed:
        chunks.extend(
            [
                "-- >>> BEGIN SEED: seed.sql",
                "-- WARNING: Demo/test data below. Do not use this in hosted production unless intentional.",
                seed_file.read_text().rstrip(),
                "-- <<< END SEED: seed.sql",
                "",
            ]
        )

    chunks.append(FOOTER.strip())
    return "\n".join(chunks).rstrip() + "\n"


def generate_snapshots(
    migrations_dir: Path = MIGRATIONS_DIR,
    seed_file: Path = SEED_FILE,
    output_dir: Path = OUTPUT_DIR,
) -> SnapshotResult:
    migration_files = list_migration_files(migrations_dir)
    if not migration_files:
        raise FileNotFoundError(f"No migration files found in {migrations_dir}")
    if not seed_file.exists():
        raise FileNotFoundError(f"Missing seed file: {seed_file}")

    output_dir.mkdir(parents=True, exist_ok=True)

    schema_sql = render_snapshot(migration_files, include_seed=False, seed_file=seed_file)
    schema_with_seed_sql = render_snapshot(
        migration_files,
        include_seed=True,
        seed_file=seed_file,
    )

    schema_output = output_dir / "full_schema.sql"
    schema_with_seed_output = output_dir / "full_schema_with_seed.sql"

    schema_output.write_text(schema_sql)
    schema_with_seed_output.write_text(schema_with_seed_sql)

    return SnapshotResult(
        migration_count=len(migration_files),
        schema_output=schema_output,
        schema_with_seed_output=schema_with_seed_output,
    )


def main() -> int:
    result = generate_snapshots()
    print(
        f"[generate-supabase-sql-snapshot] wrote {result.migration_count} migrations -> "
        f"{result.schema_output.relative_to(REPO_ROOT)}"
    )
    print(
        "[generate-supabase-sql-snapshot] wrote schema + seed -> "
        f"{result.schema_with_seed_output.relative_to(REPO_ROOT)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
